import fs from "node:fs";
import path from "node:path";

const pluginsDir = path.resolve("src/bot/plugins");
const output = path.resolve("src/bot/pluginRegistry.generated.ts");

const files = fs.readdirSync(pluginsDir)
  .filter((file) => file.endsWith(".ts"))
  .filter((file) => !file.startsWith("_"))
  .filter((file) => file !== "pluginManager.ts")
  .sort((a, b) => a.localeCompare(b));

const content = [
  "// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit manually.",
  "",
  "export const pluginModules = [",
  ...files.map((file) => `  () => import("./plugins/${file.replace(/\\.ts$/, ".js")}"),`),
  "];",
  "",
].join("\n");

fs.writeFileSync(output, content);
console.log(`Generated ${files.length} plugin modules -> ${output}`);
